server:
  port: 8000
  servlet:
    session:
      cookie:
        path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.49.112:3306/cms?characterEncoding=utf8&useSSL=true
    username: dbuser
    password: dbuser
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.qq.com
    username: 767868009@qq.com
    password: yyexjdipppkpbedg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapper/*.xml #配置.xml文件路径
  type-aliases-package: com.xmu.cms   #配置模型路径
file:
  folder: "D:\\temp\\"