spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.49.112:3306/cms?characterEncoding=utf8&useSSL=true
    username: dbuser
    password: dbuser
mybatis:
  mapper-locations: classpath:mapper/*.xml #配置.xml文件路径
  type-aliases-package: com.xmu.cms   #配置模型路径
